Update R8 to fix `NoSuchMethodError` crash (#914)
(cherry picked from commit 8e4a1062ed9a8358029e724b377a7085b110aec6)

# Conflicts:
#	build.gradle.kts